name: C Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile
        run: gcc -Wall -Wextra -std=c11 main.c -o blood_system
